### ISSUE TITLE
Rename calculated columns

### ISSUE THREAD

**Issue by bartaelterman** [LifeWatchINBO/uva-bits-etl#1]
new column names:

* `time_diff`
* `distance_diff`
* `speed` (this one should be in m / s)

**Comment by peterdesmet** [comment]
Maybe rename speed to `speed_2d`

**Comment by bartaelterman** [comment]
@peterdesmet `speed_2d` is actually already in the dataset. I guess it's not the intention to overwrite that column. Suggestion for a new name?

**Comment by peterdesmet** [comment]
Can't we have a domainspace for our names and/or the source data?

    inbo_speed_2d
    speed_2d (of uva_speed_2d)

Otherwise we can call it `horizontal_speed`.

**Comment by bartaelterman** [comment]
I'm in favor of the name space. `inbo_speed_2d` it is. I'll prefix our other calculated columns with `inbo_` as well. That makes it clear what we calculated, and what was present in the UvA-BiTS data.

**Comment by peterdesmet** [comment]
Ok, and not prefix the other (uva) columns, so all existing queries can continue to work.

**Comment by bartaelterman** [comment]
@peterdesmet  does our meeting yesterday change anything here? Maybe we should use a different prefix?

**Comment by bartaelterman** [comment]
We'll replace `inbo_` with `calc_`
