### ISSUE TITLE
Documentation on input fields needed

### ISSUE THREAD

**Issue by bartaelterman** [LifeWatchINBO/uva-bits-etl#2]
See question marks in [the vignette](https://github.com/LifeWatchINBO/uva-bits-etl/blob/master/vignettes/uva-bits-etl.Rmd#tracking-data)

- [ ] Units for field `pressure`: "Pressure measured by GPS tag sensor in Pascals"
- [ ] Description for field `positiondop`: "Positional DOP (Dilution of Precision), unitless"
- [ ] Units for `speed_accuracy`: Not documented
- [ ] Description for field `location`: "postgreSQL geometry; to allow GIS operations"
- [ ] Description for field `userflag` preferably including how it is computed: "Acceptable = 0; Data flagged as unacceptable by user if not equal to 0."
- [ ] Description and units for field `speed_3d`: "sqrt(d.x_speed^2 + d.y_speed^2 + d.z_speed^2), m/s"
- [ ] Description and units for field `speed_2d`: "Speed on 2D, m/s"
- [ ] Description and units for field `altitude_agl`: "Reported GPS altitude MINUS terrain elevation on the coordinate based on Digital Elevation Model data used in the e-ecology database"

**Comment by peterdesmet** [comment]
I've added the definitions I found in the UvA-BiTS wiki. Note that the userflag is repurposed and should now have a different definition.
