### ISSUE TITLE
day_or_night field requested

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/uva-bits-etl#4]
Add a `day_or_night` field and populate for each occurrence. What service could we use for this?

**Comment by bartaelterman** [comment]
Done. Used the `sunriset` function from the `maptools` package. I wrote a small wrapper function around it and [tested its outcome](https://github.com/LifeWatchINBO/uva-bits-etl/blob/master/tests/testthat/test_enrich.R#L22).

The resulting field is `calc_sunlight` and contains `TRUE` or `FALSE` values as documented [here](https://github.com/LifeWatchINBO/uva-bits-etl/blob/master/vignettes/uva-bits-etl.Rmd#output-format)
