### ISSUE TITLE
Why not combine this repo with bird-tracking-preprocessing

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/uva-bits-etl#6]
Why is this repo not included in https://github.com/LifeWatchINBO/bird-tracking-preprocessing?

**Comment by bartaelterman** [comment]
Because I think the code in this repository is relevant to other UvA-BiTS users, whereas I don't think that is the case for the other repo. Therefore, I did not want to bury this code inside the whole AWS and pipelineing stuff.

The other repo is private, this one isn't.

**Comment by peterdesmet** [comment]
ok
